name: "游냍 Bug"
description: Criar um relat칩rio de bug para nos ajudar a melhorar
title: "游냍 [BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Descri칞칚o do Bug"
      description: Por favor, forne칞a uma descri칞칚o curta e expl칤cita do seu incidente...
      placeholder: "Ex: O bot칚o '...' n칚o est치 funcionando corretamente"
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Passos para reproduzir"
      description: Descreva os passos para reproduzir o bug...
      value: |
        1. Acesse a p치gina '....'
        2. Clique em '....'
        3. V치 para '....'
        4. Dispare o evento '....'
        5. O erro ocorre...
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: Se houver, adicione capturas de tela para ajudar a explicar o problema...
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Se houver, adicione logs para ajudar a explicar o problema...
      render: bash
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: "Navegadores"
      description: Quais navegadores est칚o impactados ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: Qual sistema operacional est치 impactado ?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false
