name: "Generate Gitmoji Changelog"
on:
  - push
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - name: "Generate Changelog"
        uses: sercanuste/gitmoji-changelog-action@v1
